#!/usr/bin/env python
from neovim import attach
import os, sys

args = sys.argv[1:]
if not args:
    print "Usage: {} <filename> ...".format(sys.argv[0])
    sys.exit(1)

addr = os.environ["NVIM_LISTEN_ADDRESS"]
if not addr:
    # TODO: Open a new nvim instance if no addr
    sys.exit(2)

import os.path

import thread
nvim = attach("socket", path=addr)
def normalizePath(name):
    return os.path.abspath(name).replace(" ", "\\ ")

def openFiles():
    # To escape terminal mode. Not sure if bug.
    nvim.feedkeys('', "n")
    for x in args:
        nvim.command("drop {}".format(normalizePath(x)))

openFiles()
