#!/bin/bash
# Author: Ashkan Kiani
# Version: 0.1.4
# Description: Runs actions based on your clipboard using pbpaste

# Plans:
# - Allow specifying actions with a parameter (-a action)
# - Improve auto detecting the action
# - Dance.
CYAN="\033[0;36m"
RED="\033[0;31m"
BLUE="\033[0;34m"
NO_COLOUR="\033[0m"

content="$(pbpaste)"

matches() {
  echo "$1" | grep -E "$2" >/dev/null
}
isGitURL() {
  matches "$1" 'github\.com|\.git$'
}
Message() {
  echo -e "$BLUE${*}$NO_COLOUR" >&2
}

# Run git clone for git urls.
# TODO: test for proper url format.
isGitURL "$content" && {
  Message "Github url; cloning:"
  if matches "$content" "vim"; then
    pushd ~/.vim/bundle
  else
    pushd .
  fi

  git clone "$content"
  status=$?
  popd
  exit $status
}

# Default action is just to echo
Message "Default action (echo):"
echo "$content"

